from enum import StrEnum


class Scene(StrEnum):
    COMBAT = "combat"
    CARD_SELECTION = "card_selection"
    CARD_REWARD = "card_reward"
    SHOP = "shop"
    REST = "rest"
    MAP = "map"
    EVENT = "event"
    TREASURE = "treasure"
    MAIN_MENU = "main_menu"
    CHARACTER_SELECT = "character_select"
    MODAL = "modal"
    GAME_OVER = "game_over"
    UNKNOWN = "unknown"


class ActionKind(StrEnum):
    PLAY_CARD = "play_card"
    END_TURN = "end_turn"
    CHOOSE_CARD = "choose_card"
    OPEN_CARD_REWARD = "open_card_reward"
    CLAIM_REWARD = "claim_reward"
    DISCARD_POTION = "discard_potion"
    CHOOSE_MAP_NODE = "choose_map_node"
    BUY_ITEM = "buy_item"
    REMOVE_CARD = "remove_card"
    UPGRADE_CARD = "upgrade_card"
    CHOOSE_EVENT_OPTION = "choose_event_option"
    USE_POTION = "use_potion"
    SELECT_CARD = "select_card"
    CONFIRM_SELECTION = "confirm_selection"
    SELECT_CARD_BUNDLE = "select_card_bundle"
    SKIP = "skip"
    PROCEED = "proceed"
    REST = "rest"
    SELECT_CHARACTER = "select_character"
    EMBARK = "embark"
    OPEN_RUN = "open_run"
    CONTINUE_RUN = "continue_run"
    CHOOSE_TREASURE_RELIC = "choose_treasure_relic"
    OPEN_CHEST = "open_chest"
    OPEN_SHOP = "open_shop"
    CLOSE_SHOP = "close_shop"
    OPEN_TIMELINE = "open_timeline"
    CLOSE_MENU = "close_menu"
    RETURN_TO_MAIN_MENU = "return_to_main_menu"
    OTHER = "other"
